### ISSUE TITLE
Run exporter occur: error while loading shared libraries: libdl.so.2

### ISSUE THREAD

**Issue by pytimer** [prometheus/busybox#15]
Hi, i write a demo exporter, i build it with `promu` on Ubuntu16.04, it can works on host.

I want to build docker images for this exporter, but when run container, `docker logs` have a problem.

```
/bin/gpu_exporter: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory
```

I use `quay.io/prometheus/busybox:glibc`, this image have no `libdl.so.2`, i want to know is it build command wrong?

This my Dockerfile:

```Dockerfile
FROM quay.io/prometheus/golang-builder as builder

COPY ./promu /bin/promu
ADD . /go/src/github.com/pytimer/gpu_exporter
WORKDIR /go/src/github.com/pytimer/gpu_exporter
RUN /bin/promu build -v

FROM  quay.io/prometheus/busybox:glibc

COPY --from=builder /go/src/github.com/pytimer/gpu_exporter/gpu_exporter /bin/gpu_exporter

EXPOSE      9470
USER        nobody
CMD  [ "/bin/gpu_exporter" ]
```

promu.yml:

```yml
go: 
  version: 1.10.3
  cgo: true
repository:
  path: github.com/pytimer/gpu_exporter
build:
  binaries:
    - name: gpu_exporter
  flags: -a -tags 'netgo static_build'
  ldflags: |
    -X {{repoPath}}/main.Version={{.Version}}
crossbuild:
  platforms:
    - linux/amd64
```
