### ISSUE TITLE
DNS resultion / nslookup fails with :latest (uClibc)

### ISSUE THREAD

**Issue by m-kraus** [prometheus/busybox#18]
I ran into this issue while modelling a demo setup using docker-compose and multiple networks: newer Thanos images as well as Prometheus images starting from 2.4.3 based upon this image were not able to resolve addresses in docker-compose.

Digging down the error i found out that using Prometheus image 2.4.2 nslookup was still working, whereas with 2.4.3 and onwards it seemed broken.

I then compared the uclib and glibc version of this image and found out, that it still works with the glibc version.

Here's a ```docker-compose.yml``` file to reproduce:
```
version: "3.5"

networks:
  whole:

services:
  hostone:
    image: quay.io/prometheus/busybox:latest
    ports: []
    networks:
      - whole
    volumes: []
    environment: []
    entrypoint: sh
    command:
    - -c
    - while sleep 2 ; do nslookup hosttwo ; echo ----- ; done
  hosttwo:
    image: quay.io/prometheus/busybox:glibc
    ports: []
    networks:
      - whole
    volumes: []
    environment: []
    entrypoint: sh
    command:
    - -c
    - while sleep 2 ; do nslookup hostone ; echo ----- ; done
```

This is the output:
```
...
issue_dns_hostone_1 | Server:		127.0.0.11
issue_dns_hostone_1 | Address:	127.0.0.11:53
issue_dns_hostone_1 |
issue_dns_hostone_1 | Non-authoritative answer:
issue_dns_hostone_1 |
issue_dns_hostone_1 | *** Can't find hosttwo: No answer
issue_dns_hostone_1 |
issue_dns_hostone_1 | -----
issue_dns_hosttwo_1 | Server:		127.0.0.11
issue_dns_hosttwo_1 | Address:	127.0.0.11:53
issue_dns_hosttwo_1 |
issue_dns_hosttwo_1 | Non-authoritative answer:
issue_dns_hosttwo_1 |
issue_dns_hosttwo_1 | Non-authoritative answer:
issue_dns_hosttwo_1 | Name:	hostone
issue_dns_hosttwo_1 | Address: 172.29.0.3
issue_dns_hosttwo_1 |
issue_dns_hosttwo_1 | -----
...
```

Maybe the commits 52dbfa4 and 0134a71 are releated to this issue - the fact that Prometheus 2.4.2 still works and 2.4.3 not could correlate to this by time.

Thank you and best regards,
Michael
