### ISSUE TITLE
Switch :latest to glibc to address DNS lookup problems

### ISSUE THREAD

**Issue by ustaerk** [prometheus/busybox#48]
Hi there,

#18 still is an issue as DNS lookup still seems to be broken in the uclib version of upstream (see below). As the Prometheus images are based on prom/busybox:latest they are based on the broken uclib version of upstream as well, causing issues with service discovery in docker compose setups. Is there any chance you could switch to the glibc version for :latest instead of uclib?

docker-compose.yml:
```
version: "3.8"
services:
  one:
    image: quay.io/prometheus/busybox:latest
    networks:
      - test-net
    entrypoint: sh
    command:
      - -c
      - while sleep 2; do nslookup two; echo XXXXXXXXXXXXX; done
  two:
    image: quay.io/prometheus/busybox:glibc
    networks:
      - test-net
    entrypoint: sh
    command:
      - -c
      - while sleep 2; do nslookup one; echo XXXXXXXXXXXXX; done
networks:
  test-net:
```

Sample output:
```
test-one-1  | Server:		127.0.0.11
test-one-1  | Address:	127.0.0.11:53
test-one-1  | 
test-one-1  | Non-authoritative answer:
test-one-1  | 
test-one-1  | *** Can't find two: No answer
test-one-1  | 
test-one-1  | XXXXXXXXXXXXX
test-two-1  | Server:		127.0.0.11
test-two-1  | Address:	127.0.0.11:53
test-two-1  | 
test-two-1  | Non-authoritative answer:
test-two-1  | Name:	one
test-two-1  | Address: 172.24.0.2
test-two-1  | 
test-two-1  | Non-authoritative answer:
test-two-1  | 
test-two-1  | XXXXXXXXXXXXX
```
